apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record
  labels:
    app: patient-record
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record
  template:
    metadata:
      labels:
        app: patient-record
    spec:
      containers:
      - name: patient-record
        image: us-central1-docker.pkg.dev/pure-fold-445308-t2/patient-record/patient-service:latest
        ports:
        - containerPort: 3001
        volumeMounts:
          - name: mongo-cert-volume
            mountPath: "."
            readOnly: true
      volumes:
        - name: mongo-cert-volume
          secret:
            secretName: mongodb-service-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: us-central1-docker.pkg.dev/pure-fold-445308-t2/appointment-service/appointment-service:latest
        ports:
        - containerPort: 3002
        volumeMounts:
          - name: mongo-cert-volume
            mountPath: "."
            readOnly: true
      volumes:
        - name: mongo-cert-volume
          secret:
            secretName: mongodb-service-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: gcr.io/pure-fold-445308-t2/notification-service:latest
        ports:
        - containerPort: 3003
        volumeMounts:
          - name: mongo-cert-volume
            mountPath: "."
            readOnly: true
      volumes:
        - name: mongo-cert-volume
          secret:
            secretName: mongodb-service-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  labels:
    app: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: gcr.io/pure-fold-445308-t2/reporting-service:latest
        ports:
        - containerPort: 3004
        volumeMounts:
          - name: mongo-cert-volume
            mountPath: "."
            readOnly: true
      volumes:
        - name: mongo-cert-volume
          secret:
            secretName: mongodb-service-role
