apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medi-track-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Strips /patient-records prefix
spec:
  defaultBackend:
    service:
      name: patient-record
      port:
        number: 80

  rules:
  - http:
      paths:
      - path: /appointment    # Path for appointment service
        pathType: Prefix
        backend:
          service:
            name: appointment-service  # Service name for appointments
            port:
              number: 80         # Port of the appointment service
      - path: /patient-record    # Path for patient record service
        pathType: Prefix
        backend:
          service:
            name: patient-record   # Service name for patient records
            port:
              number: 80         # Port of the patient record services
