apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: patient-record
        image: gcr.io/pure-fold-445308-t2/notification-service:latest
        ports:
        - containerPort: 5002
        volumeMounts:
          - name: mongo-cert-volume
            mountPath: "secrete/"
            readOnly: true
      volumes:
        - name: mongo-cert-volume
          secret:
            secretName: mongodb-service-role


