version: '3.8'
services:
  smtp-relay:
    image: namshi/smtp
    container_name: smtp-relay
    ports:
      - "25:25"
    environment:
      - RELAY_NETWORKS=192.168.0.0/24
      - SMTP_HOSTNAME=smtp-relay.local
      - ACCEPTED_NETWORKS=0.0.0.0/0

  flask-app:
    build:
      context: .
    container_name: flask-app
    environment:
      - SMTP_SERVER=smtp-relay
      - SMTP_PORT=25
    depends_on:
      - smtp-relay
    ports:
      - "5000:5000"
